language: python

python:
  - '3.6'

services:
  - postgresql

env:
  - MINI_KUBE_SETTINGS=uks.settings_mini_kube

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE kubernetes_django;" -U postgres

script:
  - python manage.py check --settings $MINI_KUBE_SETTINGS
  - python manage.py makemigrations uxhub --settings $MINI_KUBE_SETTINGS
  - python manage.py migrate --settings $MINI_KUBE_SETTINGS
  - python manage.py test projects/tests
  - python manage.py test milestones/tests
  - python manage.py test events/tests
  
before_install:
  - docker --version
  - docker build -t lukajvnv/uxhub_django:latest .
  - docker images
  
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/uxhub_django:latest


