{
 "title": "Django Prometheus",
 "description": "Django metrics dashboard for prometheus using django-prometheus metrics: https://github.com/korfuri/django-prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(django_db_new_connections_total, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Http response body bucket total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_responses_body_total_bytes_bucket[5m])) by (le))",
     "legendFormat": "Http response body total"
    }
   ]
  },
  {
   "title": "200 Responses sum rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"2.+\",service=~\"^$service$\"}[30s]))"
    },
    {
     "expr": "sum(rate(django_http_responses_total_by_status_total{status=\"200\"}[5m]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(django_http_responses_total_by_status_total{status=\"404\"})"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_http_responses_total_by_status_total{status=\"200\"}",
     "legendFormat": "status 200"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"404\"}",
     "legendFormat": "status 404"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"302\"}",
     "legendFormat": "status 302"
    }
   ]
  },
  {
   "title": "Migrations stats",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "django_migrations_applied_total"
    },
    {
     "expr": "django_migrations_unapplied_total"
    }
   ]
  },
  {
   "title": "Request Latency by view method bucket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{service=~\"^$service$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{service=~\"^$service$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{service=~\"^$service$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{service=~\"^$service$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=99.9"
    }
   ]
  },
  {
   "title": "Logs invoked rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_custom_issue_logs_invoked_total[5m])",
     "legendFormat": "{instance=\"django-service:80\",job=\"django-service\", issue}"
    },
    {
     "expr": "rate(django_custom_milestone_logs_invoked_total[5m])",
     "legendFormat": "{instance=\"django-service:80\",job=\"django-service\", milestone}"
    }
   ]
  },
  {
   "title": "Response total by template name",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "django_http_responses_total_by_templatename_total{templatename=\"['home.html']\"}",
     "legendFormat": "home.html"
    },
    {
     "expr": "django_http_responses_total_by_templatename_total{templatename=\"['health_check/index.html']\"}",
     "legendFormat": "health_check/index.html"
    },
    {
     "expr": "django_http_responses_total_by_templatename_total{templatename=\"['registration/login.html']\"}",
     "legendFormat": "login.html"
    },
    {
     "expr": "django_http_responses_total_by_templatename_total{templatename=\"['uxhub/milestone_list.html']\"}",
     "legendFormat": "milestone_list.html"
    },
    {
     "expr": "django_http_responses_total_by_templatename_total{templatename=\"['uxhub/milestone_detail.html']\"}",
     "legendFormat": "milestone_detail.html"
    },
    {
     "expr": "django_http_responses_total_by_templatename_total{templatename=\"['uxhub/milestone_log.html']\"}",
     "legendFormat": "milestone_log.html"
    },
    {
     "expr": "django_http_responses_total_by_templatename_total{templatename=\"['uxhub/milestone_form.html']\"}",
     "legendFormat": "milestone_form.html"
    },
    {
     "expr": "django_http_responses_total_by_templatename_total{templatename=\"['uxhub/milestone_confirm_delete.html']\"}",
     "legendFormat": "milestone_confirm_delete.html"
    }
   ]
  },
  {
   "title": "Requests latency middleware seconds bucket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket[5m])) by (le))",
     "legendFormat": "le=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket[5m])) by (le))",
     "legendFormat": "le=0.95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket[5m])) by (le))",
     "legendFormat": "le=0.75"
    }
   ]
  },
  {
   "title": "Http requests by method",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "count(django_http_requests_total_by_method_created{method=\"POST\", instance=\"django-service:80\", job=\"django-service\"})"
    },
    {
     "expr": "count(django_http_requests_total_by_method_created{method=\"GET\", instance=\"django-service:80\", job=\"django-service\"})"
    },
    {
     "expr": "django_http_requests_total_by_method_total{method=\"GET\"}"
    },
    {
     "expr": "django_http_requests_total_by_method_total{method=\"POST\"}"
    }
   ]
  }
 ]
}