# Generated by Django 2.2.10 on 2020-03-03 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('approximated_time', models.IntegerField()),
                ('invested_time', models.IntegerField()),
                ('completion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uxhub.User')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('git_repository_url', models.URLField()),
                ('collaborators', models.ManyToManyField(related_name='collaborators', to='uxhub.User')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('issues', models.ManyToManyField(to='uxhub.Issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ManyToManyField(to='uxhub.User'),
        ),
        migrations.AddField(
            model_name='issue',
            name='milestones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Milestone'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Project'),
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('invested_time', models.TimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.User')),
                ('issues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uxhub.Issue')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=400)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User')),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangingMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('name', models.CharField(default='', max_length=200)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User')),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Issue')),
                ('milestones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.Milestone')),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uxhub.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangingIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('new_state', models.CharField(choices=[('TO_DO', 'To do'), ('OPENED', 'Opened'), ('FEEDBACK', 'Requested feedback'), ('CLOSED', 'Closed')], default='TO_DO', max_length=8)),
                ('assignees', models.ManyToManyField(related_name='issue_assignees', to='uxhub.User')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User')),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=400)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.Comment')),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
