# Generated by Django 3.0.3 on 2020-02-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('approximated_time', models.TimeField()),
                ('invested_time', models.TimeField()),
                ('completion', models.IntegerField()),
                ('issue_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('git_repository_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('issues', models.ManyToManyField(to='uxhub.Issue')),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.Project')),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='uxhub.User')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=20)),
                ('label_color', models.CharField(max_length=20)),
                ('issues', models.ManyToManyField(to='uxhub.Issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='milestones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Milestone'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Project'),
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('invested_time', models.TimeField()),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=400)),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Issue')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Issue')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangingMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Issue')),
                ('milestones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.Milestone')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('comment', models.CharField(max_length=400)),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Issue')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangingAssignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uxhub.Issue')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
