# Generated by Django 3.0.3 on 2020-02-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uxhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.AddField(
            model_name='issue',
            name='users',
            field=models.ManyToManyField(to='uxhub.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uxhub.User'),
        ),
    ]
