# Generated by Django 3.0.3 on 2020-02-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uxhub', '0002_auto_20200216_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
