# Generated by Django 3.0.3 on 2020-02-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uxhub', '0003_auto_20200216_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
