# Generated by Django 3.0.3 on 2020-02-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uxhub', '0004_milestone_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_name',
            new_name='name',
        ),
    ]
