# Generated by Django 3.0.3 on 2020-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uxhub', '0005_auto_20200217_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='users',
            field=models.ManyToManyField(null=True, to='uxhub.User'),
        ),
    ]
