# Generated by Django 3.0.3 on 2020-02-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uxhub', '0006_auto_20200217_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='approximated_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='invested_time',
            field=models.IntegerField(),
        ),
    ]
