# Generated by Django 3.0.3 on 2020-02-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uxhub', '0007_auto_20200217_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='completion',
            field=models.BooleanField(),
        ),
    ]
